### PR TITLE
Handling swf headers, fps propagation, dynamic version output

### PR DESCRIPTION
**Pull request by tbrebant**
- SWF headers are now handled.
- Exported JSON now respects original files framerate when it's possible (resolves https://github.com/Wizcorp/Jeff/issues/31).
- Exported JSON's version is now dynamic.

Ping @bchevalier @dyoxyne @cstoquer @cainmartin.

### CODE REVIEW

**Comment by bchevalier** [comment]
lgtm!

**Comment by tbrebant** [comment]
Can you point me out where?

**Comment by bchevalier** [comment]
I am adding those changes to Jeff v3, will make a PR today so you can have a look. I will be attaching the frame rate to symbols (as opposed to graphics).

**Comment by tbrebant** [comment]
Thank you for the review. I checked how you did in 0.3, I think this would require some refactor on 0.1 branch to do it properly. Because it's smarter and more productive to focus on latest version (I'll start giving my feedbacks on your PR today!) I just added a comment explaining how it would be done better.

**Pull request merged**
